### ISSUE TITLE
Is there a way to forbid future unseal-ing of the keyfile after boot

### ISSUE THREAD

**Issue by gdamjan** [electrickite/mkinitcpio-tpm2-encrypt#4]
I wonder if there's an approach to forbid unsealing the keyfile after a succesful unsealing at boot is done?

**Comment by electrickite** [comment]
Yes, with the `tpmextend` parameter: https://github.com/electrickite/mkinitcpio-tpm2-encrypt#tpmextend

It will extend a PCR _after_ unsealing the key. 

As an example, let’s assume PCR 0, 2, and 7 are used by your system to measure boot configuration and the kernel image. Let’s also assume PCR 8 is unused.

You can seal the key against `sha1:0,2,7,8` when PCR 8 is empty. Then use `tpmextend=sha1:8` to measure a value into PCR 8 on boot. This will prevent the key from being unsealed after the hook runs, because PCR 8 is in a different state than when it was sealed.

**Comment by gdamjan** [comment]
Thanks. I'll try this
